spring:

  profiles:
    active:
      - dev

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  main:
    banner-mode: off

mybatis:
  type-aliases-package: com.xazhao.**.entity, com.xazhao.**.dto
  mapper-locations: classpath*:mappers/**/*Mapper.xml
  config-location: classpath:mybatis-config.xml

com:
  xazhao:
    custom:
      cache: true
